# Generated by Django 5.0 on 2024-06-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_passengers',
        ),
        migrations.AddField(
            model_name='order',
            name='additional_passenger_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='additional_passenger_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='airline',
            field=models.CharField(max_length=255),
        ),
    ]
