# Generated by Django 5.0 on 2024-06-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destination',
            new_name='flying_to',
        ),
    ]
